<?php

declare(strict_types=1);

use Phinx\Db\Table\Column;
use Phinx\Migration\AbstractMigration;

final class WaRules extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * https://book.cakephp.org/phinx/0/en/migrations.html#the-change-method
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change(): void
    {
        $table = $this->table('wa_rules', ['comment' => '权限规则']);
        $table->addColumn('title', Column::STRING, ['limit' => 255, 'comment' => '标题']);
        $table->addColumn('icon', Column::STRING, ['limit' => 255, 'comment' => '图标']);
        $table->addColumn('key', Column::STRING, ['limit' => 255, 'comment' => '标识']);
        $table->addColumn('pid', Column::INTEGER, ['signed' => false, 'default' => 0, 'comment' => '上级菜单']);
        $table->addColumn('href', Column::STRING, ['limit' => 255, 'comment' => 'url']);
        $table->addColumn('type', Column::INTEGER, ['default' => 1, 'comment' => '类型']);
        $table->addColumn('weight', Column::INTEGER, ['default' => 0, 'comment' => '排序']);
        $table->addColumn('created_at', Column::DATETIME, ['comment' => '创建时间']);
        $table->addColumn('updated_at', Column::DATETIME, ['comment' => '更新时间']);
        $table->create();

        $table->insert([
            [
                'id' => 1,
                'title' => '数据库',
                'icon' => 'layui-icon-template-1',
                'key' => 'database',
                'pid' => 0,
                'href' => null,
                'type' => 0,
                'weight' => 1000,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 2,
                'title' => '所有表',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController',
                'pid' => 1,
                'href' => '/app/admin/table/index',
                'type' => 1,
                'weight' => 800,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 3,
                'title' => '权限管理',
                'icon' => 'layui-icon-vercode',
                'key' => 'auth',
                'pid' => 0,
                'href' => null,
                'type' => 0,
                'weight' => 900,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 4,
                'title' => '账户管理',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AdminController',
                'pid' => 3,
                'href' => '/app/admin/admin/index',
                'type' => 1,
                'weight' => 1000,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 5,
                'title' => '角色管理',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\RoleController',
                'pid' => 3,
                'href' => '/app/admin/role/index',
                'type' => 1,
                'weight' => 900,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 6,
                'title' => '菜单管理',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\RuleController',
                'pid' => 3,
                'href' => '/app/admin/rule/index',
                'type' => 1,
                'weight' => 800,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 7,
                'title' => '会员管理',
                'icon' => 'layui-icon-username',
                'key' => 'user',
                'pid' => 0,
                'href' => null,
                'type' => 0,
                'weight' => 800,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 8,
                'title' => '用户',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UserController',
                'pid' => 7,
                'href' => '/app/admin/user/index',
                'type' => 1,
                'weight' => 800,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 9,
                'title' => '通用设置',
                'icon' => 'layui-icon-set',
                'key' => 'common',
                'pid' => 0,
                'href' => null,
                'type' => 0,
                'weight' => 700,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 10,
                'title' => '个人资料',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AccountController',
                'pid' => 9,
                'href' => '/app/admin/account/index',
                'type' => 1,
                'weight' => 800,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 11,
                'title' => '附件管理',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UploadController',
                'pid' => 9,
                'href' => '/app/admin/upload/index',
                'type' => 1,
                'weight' => 700,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 12,
                'title' => '字典设置',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\DictController',
                'pid' => 9,
                'href' => '/app/admin/dict/index',
                'type' => 1,
                'weight' => 600,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 13,
                'title' => '系统设置',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\ConfigController',
                'pid' => 9,
                'href' => '/app/admin/config/index',
                'type' => 1,
                'weight' => 500,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 14,
                'title' => '插件管理',
                'icon' => 'layui-icon-app',
                'key' => 'plugin',
                'pid' => 0,
                'href' => null,
                'type' => 0,
                'weight' => 600,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 15,
                'title' => '应用插件',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\PluginController',
                'pid' => 14,
                'href' => '/app/admin/plugin/index',
                'type' => 1,
                'weight' => 800,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 16,
                'title' => '开发辅助',
                'icon' => 'layui-icon-fonts-code',
                'key' => 'dev',
                'pid' => 0,
                'href' => null,
                'type' => 0,
                'weight' => 500,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 17,
                'title' => '表单构建',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\DevController',
                'pid' => 16,
                'href' => '/app/admin/dev/form-build',
                'type' => 1,
                'weight' => 800,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 18,
                'title' => '示例页面',
                'icon' => 'layui-icon-templeate-1',
                'key' => 'demos',
                'pid' => 0,
                'href' => null,
                'type' => 0,
                'weight' => 400,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 19,
                'title' => '工作空间',
                'icon' => 'layui-icon-console',
                'key' => 'demo1',
                'pid' => 18,
                'href' => '',
                'type' => 0,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 20,
                'title' => '控制后台',
                'icon' => 'layui-icon-console',
                'key' => 'demo10',
                'pid' => 19,
                'href' => '/app/admin/demos/console/console1.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 21,
                'title' => '数据分析',
                'icon' => 'layui-icon-console',
                'key' => 'demo13',
                'pid' => 19,
                'href' => '/app/admin/demos/console/console2.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 22,
                'title' => '百度一下',
                'icon' => 'layui-icon-console',
                'key' => 'demo14',
                'pid' => 19,
                'href' => 'http://www.baidu.com',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 23,
                'title' => '主题预览',
                'icon' => 'layui-icon-console',
                'key' => 'demo15',
                'pid' => 19,
                'href' => '/app/admin/demos/system/theme.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 24,
                'title' => '常用组件',
                'icon' => 'layui-icon-component',
                'key' => 'demo20',
                'pid' => 18,
                'href' => '',
                'type' => 0,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 25,
                'title' => '功能按钮',
                'icon' => 'layui-icon-face-smile',
                'key' => 'demo2011',
                'pid' => 24,
                'href' => '/app/admin/demos/document/button.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 26,
                'title' => '表单集合',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2014',
                'pid' => 24,
                'href' => '/app/admin/demos/document/form.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 27,
                'title' => '字体图标',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2010',
                'pid' => 24,
                'href' => '/app/admin/demos/document/icon.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 28,
                'title' => '多选下拉',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2012',
                'pid' => 24,
                'href' => '/app/admin/demos/document/select.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 29,
                'title' => '动态标签',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2013',
                'pid' => 24,
                'href' => '/app/admin/demos/document/tag.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 30,
                'title' => '数据表格',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2031',
                'pid' => 24,
                'href' => '/app/admin/demos/document/table.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 31,
                'title' => '分布表单',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2032',
                'pid' => 24,
                'href' => '/app/admin/demos/document/step.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 32,
                'title' => '树形表格',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2033',
                'pid' => 24,
                'href' => '/app/admin/demos/document/treetable.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 33,
                'title' => '树状结构',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2034',
                'pid' => 24,
                'href' => '/app/admin/demos/document/dtree.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 34,
                'title' => '文本编辑',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2035',
                'pid' => 24,
                'href' => '/app/admin/demos/document/tinymce.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 35,
                'title' => '卡片组件',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2036',
                'pid' => 24,
                'href' => '/app/admin/demos/document/card.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 36,
                'title' => '抽屉组件',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2021',
                'pid' => 24,
                'href' => '/app/admin/demos/document/drawer.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 37,
                'title' => '消息通知',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2022',
                'pid' => 24,
                'href' => '/app/admin/demos/document/notice.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 38,
                'title' => '加载组件',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2024',
                'pid' => 24,
                'href' => '/app/admin/demos/document/loading.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 39,
                'title' => '弹层组件',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2023',
                'pid' => 24,
                'href' => '/app/admin/demos/document/popup.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 40,
                'title' => '多选项卡',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo60131',
                'pid' => 24,
                'href' => '/app/admin/demos/document/tab.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 41,
                'title' => '数据菜单',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo60132',
                'pid' => 24,
                'href' => '/app/admin/demos/document/menu.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 42,
                'title' => '哈希加密',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2041',
                'pid' => 24,
                'href' => '/app/admin/demos/document/encrypt.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 43,
                'title' => '图标选择',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2042',
                'pid' => 24,
                'href' => '/app/admin/demos/document/iconPicker.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 44,
                'title' => '省市级联',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2043',
                'pid' => 24,
                'href' => '/app/admin/demos/document/area.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 45,
                'title' => '数字滚动',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2044',
                'pid' => 24,
                'href' => '/app/admin/demos/document/count.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 46,
                'title' => '顶部返回',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo2045',
                'pid' => 24,
                'href' => '/app/admin/demos/document/topBar.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 47,
                'title' => '结果页面',
                'icon' => 'layui-icon-auz',
                'key' => 'demo666',
                'pid' => 18,
                'href' => '',
                'type' => 0,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 48,
                'title' => '成功',
                'icon' => 'layui-icon-face-smile',
                'key' => 'demo667',
                'pid' => 47,
                'href' => '/app/admin/demos/result/success.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 49,
                'title' => '失败',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo668',
                'pid' => 47,
                'href' => '/app/admin/demos/result/error.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 50,
                'title' => '错误页面',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo-error',
                'pid' => 18,
                'href' => '',
                'type' => 0,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 51,
                'title' => '403',
                'icon' => 'layui-icon-face-smile',
                'key' => 'demo403',
                'pid' => 50,
                'href' => '/app/admin/demos/error/403.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 52,
                'title' => '404',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo404',
                'pid' => 50,
                'href' => '/app/admin/demos/error/404.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 53,
                'title' => '500',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo500',
                'pid' => 50,
                'href' => '/app/admin/demos/error/500.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 54,
                'title' => '系统管理',
                'icon' => 'layui-icon-set-fill',
                'key' => 'demo-system',
                'pid' => 18,
                'href' => '',
                'type' => 0,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 55,
                'title' => '用户管理',
                'icon' => 'layui-icon-face-smile',
                'key' => 'demo601',
                'pid' => 54,
                'href' => '/app/admin/demos/system/user.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 56,
                'title' => '角色管理',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo602',
                'pid' => 54,
                'href' => '/app/admin/demos/system/role.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 57,
                'title' => '权限管理',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo603',
                'pid' => 54,
                'href' => '/app/admin/demos/system/power.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 58,
                'title' => '部门管理',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo604',
                'pid' => 54,
                'href' => '/app/admin/demos/system/deptment.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 59,
                'title' => '行为日志',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo605',
                'pid' => 54,
                'href' => '/app/admin/demos/system/log.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 60,
                'title' => '数据字典',
                'icon' => 'layui-icon-face-cry',
                'key' => 'demo606',
                'pid' => 54,
                'href' => '/app/admin/demos/system/dict.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 61,
                'title' => '常用页面',
                'icon' => 'layui-icon-template-1',
                'key' => 'demo-common',
                'pid' => 18,
                'href' => '',
                'type' => 0,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 62,
                'title' => '空白页面',
                'icon' => 'layui-icon-face-smile',
                'key' => 'demo702',
                'pid' => 61,
                'href' => '/app/admin/demos/system/space.html',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-03 17:32:03',
                'updated_at' => '2025-04-03 17:32:03'
            ],
            [
                'id' => 63,
                'title' => '查看表',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController@view',
                'pid' => 2,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 64,
                'title' => '查询表',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController@show',
                'pid' => 2,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 65,
                'title' => '创建表',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController@create',
                'pid' => 2,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 66,
                'title' => '修改表',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController@modify',
                'pid' => 2,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 67,
                'title' => '一键菜单',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController@crud',
                'pid' => 2,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 68,
                'title' => '查询记录',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController@select',
                'pid' => 2,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 69,
                'title' => '插入记录',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController@insert',
                'pid' => 2,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 70,
                'title' => '更新记录',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController@update',
                'pid' => 2,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 71,
                'title' => '删除记录',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController@delete',
                'pid' => 2,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 72,
                'title' => '删除表',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController@drop',
                'pid' => 2,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 73,
                'title' => '表摘要',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\TableController@schema',
                'pid' => 2,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 74,
                'title' => '插入',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AdminController@insert',
                'pid' => 4,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 75,
                'title' => '更新',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AdminController@update',
                'pid' => 4,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 76,
                'title' => '删除',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AdminController@delete',
                'pid' => 4,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 77,
                'title' => '插入',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\RoleController@insert',
                'pid' => 5,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 78,
                'title' => '更新',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\RoleController@update',
                'pid' => 5,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 79,
                'title' => '删除',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\RoleController@delete',
                'pid' => 5,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 80,
                'title' => '获取角色权限',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\RoleController@rules',
                'pid' => 5,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 81,
                'title' => '查询',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\RuleController@select',
                'pid' => 6,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 82,
                'title' => '添加',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\RuleController@insert',
                'pid' => 6,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 83,
                'title' => '更新',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\RuleController@update',
                'pid' => 6,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 84,
                'title' => '删除',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\RuleController@delete',
                'pid' => 6,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 85,
                'title' => '插入',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UserController@insert',
                'pid' => 8,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 86,
                'title' => '更新',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UserController@update',
                'pid' => 8,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 87,
                'title' => '查询',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UserController@select',
                'pid' => 8,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 88,
                'title' => '删除',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UserController@delete',
                'pid' => 8,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 89,
                'title' => '更新',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AccountController@update',
                'pid' => 10,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 90,
                'title' => '修改密码',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AccountController@password',
                'pid' => 10,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 91,
                'title' => '查询',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AccountController@select',
                'pid' => 10,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 92,
                'title' => '添加',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AccountController@insert',
                'pid' => 10,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 93,
                'title' => '删除',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AccountController@delete',
                'pid' => 10,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 94,
                'title' => '浏览附件',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UploadController@attachment',
                'pid' => 11,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 95,
                'title' => '查询附件',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UploadController@select',
                'pid' => 11,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 96,
                'title' => '更新附件',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UploadController@update',
                'pid' => 11,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 97,
                'title' => '添加附件',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UploadController@insert',
                'pid' => 11,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 98,
                'title' => '上传文件',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UploadController@file',
                'pid' => 11,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 99,
                'title' => '上传图片',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UploadController@image',
                'pid' => 11,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 100,
                'title' => '上传头像',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UploadController@avatar',
                'pid' => 11,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 101,
                'title' => '删除附件',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\UploadController@delete',
                'pid' => 11,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 102,
                'title' => '查询',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\DictController@select',
                'pid' => 12,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 103,
                'title' => '插入',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\DictController@insert',
                'pid' => 12,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 104,
                'title' => '更新',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\DictController@update',
                'pid' => 12,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 105,
                'title' => '删除',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\DictController@delete',
                'pid' => 12,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 106,
                'title' => '更改',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\ConfigController@update',
                'pid' => 13,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 107,
                'title' => '列表',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\PluginController@list',
                'pid' => 15,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 108,
                'title' => '安装',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\PluginController@install',
                'pid' => 15,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 109,
                'title' => '卸载',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\PluginController@uninstall',
                'pid' => 15,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 110,
                'title' => '支付',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\PluginController@pay',
                'pid' => 15,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 111,
                'title' => '登录官网',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\PluginController@login',
                'pid' => 15,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 112,
                'title' => '获取已安装的插件列表',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\PluginController@getInstalledPlugins',
                'pid' => 15,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 113,
                'title' => '表单构建',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\DevController@formBuild',
                'pid' => 17,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-03 17:51:36',
                'updated_at' => '2025-04-03 17:51:36'
            ],
            [
                'id' => 114,
                'title' => '验证码',
                'icon' => 'layui-icon-cellphone',
                'key' => 'plugin\admin\app\controller\AppSmsController',
                'pid' => 132,
                'href' => '/app/admin/app-sms/index',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-07 21:26:59',
                'updated_at' => '2025-04-08 10:09:25'
            ],
            [
                'id' => 121,
                'title' => 'selectType',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AppSmsController@selectType',
                'pid' => 114,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-07 22:31:26',
                'updated_at' => '2025-04-07 22:31:26'
            ],
            [
                'id' => 122,
                'title' => 'selectApp',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AppSmsController@selectApp',
                'pid' => 114,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-07 22:31:26',
                'updated_at' => '2025-04-07 22:31:26'
            ],
            [
                'id' => 123,
                'title' => 'select',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AppSmsController@select',
                'pid' => 114,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-07 22:31:26',
                'updated_at' => '2025-04-21 16:57:36'
            ],
            [
                'id' => 127,
                'title' => '授权管理',
                'icon' => 'layui-icon-vercode',
                'key' => 'plugin\admin\app\controller\AppSmsTokenController',
                'pid' => 132,
                'href' => '/app/admin/app-sms-token/index',
                'type' => 1,
                'weight' => 0,
                'created_at' => '2025-04-08 10:08:05',
                'updated_at' => '2025-04-08 10:09:42'
            ],
            [
                'id' => 128,
                'title' => '插入',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AppSmsTokenController@insert',
                'pid' => 127,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-08 10:08:11',
                'updated_at' => '2025-04-08 10:08:11'
            ],
            [
                'id' => 129,
                'title' => '更新',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AppSmsTokenController@update',
                'pid' => 127,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-08 10:08:11',
                'updated_at' => '2025-04-08 10:08:11'
            ],
            [
                'id' => 130,
                'title' => 'select',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AppSmsTokenController@select',
                'pid' => 127,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-08 10:08:11',
                'updated_at' => '2025-04-21 16:57:36'
            ],
            [
                'id' => 131,
                'title' => 'delete',
                'icon' => null,
                'key' => 'plugin\admin\app\controller\AppSmsTokenController@delete',
                'pid' => 127,
                'href' => null,
                'type' => 2,
                'weight' => 0,
                'created_at' => '2025-04-08 10:08:11',
                'updated_at' => '2025-04-21 16:57:36'
            ],
            [
                'id' => 132,
                'title' => 'APP验证码',
                'icon' => 'layui-icon-cellphone',
                'key' => 'app-sms',
                'pid' => 0,
                'href' => '',
                'type' => 0,
                'weight' => 0,
                'created_at' => '2025-04-08 10:08:42',
                'updated_at' => '2025-04-08 10:08:42'
            ]
        ]);
        $table->saveData();
    }
}
